### ISSUE TITLE
Fedora/RHEL requirements

### ISSUE THREAD

**Issue by birdie-github** [0xABADCAFE/php-demo-engine#47]
Please add this to the description.

```
In order to be able to run the demo under Fedora/RHEL you need to install PHP and its dependencies:

sudo dnf install php-cli php-json php-process
```

**Comment by 0xABADCAFE** [comment]
Thanks for the suggestion.

I've updated the main readme to include the specific php packages necessary rather than include specifics for installing them on a given OS / distribution. I think it's a safe assumption that most people looking to test this will know how to install the required packages for their OS of choice.
